### ISSUE TITLE
make the reference topology example work by default

### ISSUE THREAD

**Issue by seanx820** [CumulusNetworks/topology_converter#10]
this file->
https://github.com/CumulusNetworks/topology_converter/blob/master/examples/reference_topology.dot

needs to have
oob-mgmt-server changed and oob-mgmt-switch changed

oob-mgmt-server should be pointed at OOB_Server_Config.sh and oob-mgmt-switch should be pointed at OOB_Switch_Config.sh

also turn on eth0->
  #echo -e "\n\nauto eth0" > /etc/network/interfaces.d/eth0.cfg
    #echo -e "iface eth0 inet dhcp\n\n" >> /etc/network/interfaces.d/eth0.cfg

uncomment this for both oob-mgmt-switch and oob-mgmt-server

**Comment by ericpulvino** [comment]
This is a good idea. I will get this done as part of the 4.2.0 release.

**Comment by ericpulvino** [comment]
Pushed to v4.3.0

**Comment by ericpulvino** [comment]
Removed the reference topology example as part of v4.3.0 so this is no longer relevant. Didn't want to keep the reference topo in two places and risk having this one fall out of date. Will consider adding the MGMT network to all example content if you think it makes sense.
