### ISSUE TITLE
udev renaming does not work in CentOS/RHEL 7.X

### ISSUE THREAD

**Issue by seanx820** [CumulusNetworks/topology_converter#11]
Info:

- https://access.redhat.com/solutions/1422203
- https://bugzilla.redhat.com/show_bug.cgi?id=997573#c1
- https://bbs.archlinux.org/viewtopic.php?pid=1138526#p1138526
- http://askubuntu.com/questions/187251/udev-webcam-rule-read-but-not-respected
- https://github.com/systemd/systemd/issues/2657

fix so far is to have another script e.g.
```
[root@server01 rules.d]# cat 68.rules
ACTION=="add", SUBSYSTEM=="net", ATTR{address}=="a0:00:00:00:00:31", NAME="lexi", SUBSYSTEMS=="pci"
ACTION=="add", SUBSYSTEM=="net", ATTR{address}=="44:38:39:00:00:1e", NAME="dora", SUBSYSTEMS=="pci"
ACTION=="add", SUBSYSTEM=="net", ATTR{address}=="44:38:39:00:00:0b", NAME="zoey", SUBSYSTEMS=="pci"
ACTION=="add", SUBSYSTEM=="net", ATTR{address}=="52:54:00:96:1d:95", NAME="aria", SUBSYSTEMS=="pci"
```
then the real rename script at a high priority 
```
[root@server01 rules.d]# cat 71.rules
ACTION=="add", SUBSYSTEM=="net", ATTR{address}=="a0:00:00:00:00:31", NAME="eth0", SUBSYSTEMS=="pci"
ACTION=="add", SUBSYSTEM=="net", ATTR{address}=="44:38:39:00:00:1e", NAME="eth1", SUBSYSTEMS=="pci"
ACTION=="add", SUBSYSTEM=="net", ATTR{address}=="44:38:39:00:00:0b", NAME="eth2", SUBSYSTEMS=="pci"
ACTION=="add", SUBSYSTEM=="net", ATTR{address}=="52:54:00:96:1d:95", NAME="vagrant", SUBSYSTEMS=="pci"
```

**Comment by ericpulvino** [comment]
Solution is to not use the same namespace as the kernel when naming interfaces on Host OSes that are using legacy interface naming (instead of the new predictable interface naming convention).

**Comment by tsarangi** [comment]
Does this two rule script works for you on a  {{systemd}} system ? For me, it only modifies the the first set (`68.rules`), and then it doesn't even call `71.rules`.
