### ISSUE TITLE
Install python2.7 on Ubuntu hosts, if not present

### ISSUE THREAD

**Issue by sutharsan-sivapalan** [CumulusNetworks/topology_converter#112]
To check that Ubuntu Vagrant images have python2.7 installed and to install it if not present.
This is to ensure that Ansible works with the official Ubuntu images (e.g. ubuntu/xenial64) from Vagrant Cloud.

**Comment by adeg** [comment]
Should we probably consider installing python3, since python2.7 is going to be EOL in 10 months?

**Comment by ericpulvino** [comment]
The -c workflow uses the 'generic/ubuntu1804' image which ships with python already installed. If choosing to use images outside of the ones used in "functional defaults" (https://github.com/CumulusNetworks/topology_converter/blob/development/documentation/README.md#functional-defaults) the config to get that OS up and running falls squarely on the user.

Doing something like this would start a slippery slope of trying to support multiple OS configs and image builds out of the box. There are so many different image builds out there for each OS and each builder can choose to butcher them in a different way. It is well known that the ubuntu/xenial64 and really all of the ubuntu/* images are not really useful at this time. They come too devoid of basic tooling (like python) and also without the default vagrant user which is another significant foundational component to use with vagrant. I strongly recommend moving away from an image like that in favor of something in the "tested/approved" list (https://github.com/CumulusNetworks/topology_converter/blob/master/documentation/README.md#vagrant-box-selection).
