### ISSUE TITLE
New users have shell set to /bin/sh rather than /bin/bash

### ISSUE THREAD

**Issue by rdarbha** [CumulusNetworks/topology_converter#130]
The OOB_Server_Config_auto_mgmt.sh.j2 creates the `cumulus` user via the following command:
```useradd -m cumulus
```

The default shell for the cumulus user on the current box version used for teh oob-mgmt-server with the -c workflow is /bin/sh:
```
cumulus@oob-mgmt-server:~$ cat /etc/default/useradd
# Default values for useradd(8)
#
# The SHELL variable specifies the default login shell on your
# system.
# Similar to DHSELL in adduser. However, we use "sh" here because
# useradd is a low level utility and should be as general
# as possible
SHELL=/bin/sh
...
```

The command needs to be changed to `useradd -m cumulus -s /bin/bash`.

**Comment by ericpulvino** [comment]
This is one of those things I've fixed all over the place and never made it's way back into the main repo. Fixed, thanks!
