### ISSUE TITLE
Allow SSH key forwarding on oob-mgmt-server

### ISSUE THREAD

**Issue by rdarbha** [CumulusNetworks/topology_converter#134]
In order to manage repos on oob-mgmt-server, using SSH keys is a great option and is enforced when doing 2FA. Default settings don't include SSH forwarding agent when typing `vagrant ssh oob-mgmt-server`. To support this, use the following configuration

```
config.ssh.forward_agent = true
```

We should add this to the existing configuration:

```
Vagrant.configure("2") do |config|

  wbid = 1
  offset = wbid * 100

  config.ssh.forward_agent = true  <=== ADD THIS CONFIG


  config.vm.provider :libvirt do |domain|
    domain.management_network_address = "10.255.#{wbid}.0/24"
    domain.management_network_name = "wbr#{wbid}"
    # increase nic adapter count to be greater than 8 for all VMs.
    domain.nic_adapter_count = 130
  end
```

**Comment by ericpulvino** [comment]
Addressed in commit a6bfe7c.
