### ISSUE TITLE
converter won't run with extra graph line in topology.dot file

### ISSUE THREAD

**Issue by kwitherstine** [CumulusNetworks/topology_converter#17]
Having the following line in the topology.dot file will cause the script not to run:
"graph [hostidtype="hostname", version="1:0"];"

Error message:
"### ERROR: MANDATORY DEVICE ATTRIBUTE "os" not specified for graph"

********************************************************************
kevinw@Kevins-MBP-2[topology_converter]# cat topology.dot
# generic example - cumulus@leaf1$ cat /etc/ptm.d/topology.dot
graph G {
  graph [hostidtype="hostname", version="1:0"];
   "MDC1-19-DOCP-TORA" [function="leaf"]
   "MDC1-19-DOCP-TORB" [function="leaf"]
   "RR3-05-QOCP-TORA" [function="leaf"]
   "RR3-05-QOCP-TORB" [function="leaf"]
   "MTS1-20-HOCP-TORB" [function="leaf"]
   "MDC1-19-OCP-SPINEA" [function="spine"]
   "MDC1-19-OCP-SPINEB" [function="spine"]
   "MDC1-22-OCP-ACCESSA" [function="exit"]
   "MDC1-22-OCP-ACCESSB" [function="exit"]
    "MDC1-22-OCP-ACCESSA":"swp1" -- "MDC1-22-OCP-ACCESSB":"swp1";
    "MDC1-22-OCP-ACCESSA":"swp49" -- "MDC1-19-OCP-SPINEA":"swp31";
    "MDC1-22-OCP-ACCESSA":"swp50" -- "MDC1-19-OCP-SPINEB":"swp31";
    "MDC1-22-OCP-ACCESSB":"swp49" -- "MDC1-19-OCP-SPINEA":"swp32";
    "MDC1-22-OCP-ACCESSB":"swp50" -- "MDC1-19-OCP-SPINEB":"swp32";
    "MDC1-19-OCP-SPINEA":"swp1" -- "MDC1-19-OCP-SPINEB":"swp1";
    "MDC1-19-OCP-SPINEA":"swp27" -- "RR3-05-QOCP-TORA":"swp49";
    "MDC1-19-OCP-SPINEA":"swp28" -- "RR3-05-QOCP-TORB":"swp49";
    "MDC1-19-OCP-SPINEA":"swp29" -- "MDC1-19-DOCP-TORA":"swp49";
    "MDC1-19-OCP-SPINEA":"swp30" -- "MDC1-19-DOCP-TORB":"swp49";
    "MDC1-19-OCP-SPINEB":"swp27" -- "RR3-05-QOCP-TORA":"swp50";
    "MDC1-19-OCP-SPINEB":"swp28" -- "RR3-05-QOCP-TORB":"swp50";
    "MDC1-19-OCP-SPINEB":"swp29" -- "MDC1-19-DOCP-TORA":"swp50";
    "MDC1-19-OCP-SPINEB":"swp30" -- "MDC1-19-DOCP-TORB":"swp50";
    "MDC1-19-DOCP-TORA":"swp47" -- "MDC1-19-DOCP-TORB":"swp47";
    "RR3-05-QOCP-TORA":"swp51" -- "RR3-05-QOCP-TORB":"swp51";
    "RR3-05-QOCP-TORA":"swp52" -- "RR3-05-QOCP-TORB":"swp52"
}
kevinw@Kevins-MBP-2[topology_converter]# python ./topology_converter.py ./topology.dot

######################################
          Topology Converter
######################################
 ### ERROR: MANDATORY DEVICE ATTRIBUTE "os" not specified for graph
kevinw@Kevins-MBP-2[topology_converter]#

kevinw@Kevins-MBP-2[topology_converter]# cat topology.dot
# generic example - cumulus@leaf1$ cat /etc/ptm.d/topology.dot
graph G {
 "MDC1-19-DOCP-TORA" [function="leaf"]
 "MDC1-19-DOCP-TORB" [function="leaf"]
 "RR3-05-QOCP-TORA" [function="leaf"]
 "RR3-05-QOCP-TORB" [function="leaf"]
 "MTS1-20-HOCP-TORB" [function="leaf"]
 "MDC1-19-OCP-SPINEA" [function="spine"]
 "MDC1-19-OCP-SPINEB" [function="spine"]
 "MDC1-22-OCP-ACCESSA" [function="exit"]
 "MDC1-22-OCP-ACCESSB" [function="exit"]
    "MDC1-22-OCP-ACCESSA":"swp1" -- "MDC1-22-OCP-ACCESSB":"swp1";
    "MDC1-22-OCP-ACCESSA":"swp49" -- "MDC1-19-OCP-SPINEA":"swp31";
    "MDC1-22-OCP-ACCESSA":"swp50" -- "MDC1-19-OCP-SPINEB":"swp31";
    "MDC1-22-OCP-ACCESSB":"swp49" -- "MDC1-19-OCP-SPINEA":"swp32";
    "MDC1-22-OCP-ACCESSB":"swp50" -- "MDC1-19-OCP-SPINEB":"swp32";
    "MDC1-19-OCP-SPINEA":"swp1" -- "MDC1-19-OCP-SPINEB":"swp1";
    "MDC1-19-OCP-SPINEA":"swp27" -- "RR3-05-QOCP-TORA":"swp49";
    "MDC1-19-OCP-SPINEA":"swp28" -- "RR3-05-QOCP-TORB":"swp49";
    "MDC1-19-OCP-SPINEA":"swp29" -- "MDC1-19-DOCP-TORA":"swp49";
    "MDC1-19-OCP-SPINEA":"swp30" -- "MDC1-19-DOCP-TORB":"swp49";
    "MDC1-19-OCP-SPINEB":"swp27" -- "RR3-05-QOCP-TORA":"swp50";
    "MDC1-19-OCP-SPINEB":"swp28" -- "RR3-05-QOCP-TORB":"swp50";
    "MDC1-19-OCP-SPINEB":"swp29" -- "MDC1-19-DOCP-TORA":"swp50";
    "MDC1-19-OCP-SPINEB":"swp30" -- "MDC1-19-DOCP-TORB":"swp50";
    "MDC1-19-DOCP-TORA":"swp47" -- "MDC1-19-DOCP-TORB":"swp47";
    "RR3-05-QOCP-TORA":"swp51" -- "RR3-05-QOCP-TORB":"swp51";
    "RR3-05-QOCP-TORA":"swp52" -- "RR3-05-QOCP-TORB":"swp52"
}
kevinw@Kevins-MBP-2[topology_converter]# python ./topology_converter.py ./topology.dot

######################################
          Topology Converter
######################################
>> DEVICE: MDC1-22-OCP-ACCESSB
     code: CumulusCommunity/cumulus-vx
     memory: 512
     function: exit
     hostname: MDC1-22-OCP-ACCESSB
       LINK: swp1
               remote_device: MDC1-22-OCP-ACCESSA
               mac: 44:38:39:00:00:04
               network: net2
               remote_interface: swp1
       LINK: swp49
               remote_device: MDC1-19-OCP-SPINEA
               mac: 44:38:39:00:00:19
               network: net13
               remote_interface: swp32
       LINK: swp50
               remote_device: MDC1-19-OCP-SPINEB
               mac: 44:38:39:00:00:0d
               network: net7
               remote_interface: swp32
>> DEVICE: MDC1-22-OCP-ACCESSA
     code: CumulusCommunity/cumulus-vx
     memory: 512
     function: exit
     hostname: MDC1-22-OCP-ACCESSA
       LINK: swp1
               remote_device: MDC1-22-OCP-ACCESSB
               mac: 44:38:39:00:00:03
               network: net2
               remote_interface: swp1
       LINK: swp49
               remote_device: MDC1-19-OCP-SPINEA
               mac: 44:38:39:00:00:0f
               network: net8
               remote_interface: swp31
       LINK: swp50
               remote_device: MDC1-19-OCP-SPINEB
               mac: 44:38:39:00:00:11
               network: net9
               remote_interface: swp31
>> DEVICE: MDC1-19-OCP-SPINEA
     code: CumulusCommunity/cumulus-vx
     memory: 512
     function: spine
     hostname: MDC1-19-OCP-SPINEA
       LINK: swp1
               remote_device: MDC1-19-OCP-SPINEB
               mac: 44:38:39:00:00:13
               network: net10
               remote_interface: swp1
       LINK: swp27
               remote_device: RR3-05-QOCP-TORA
               mac: 44:38:39:00:00:17
               network: net12
               remote_interface: swp49
       LINK: swp28
               remote_device: RR3-05-QOCP-TORB
               mac: 44:38:39:00:00:09
               network: net5
               remote_interface: swp49
       LINK: swp29
               remote_device: MDC1-19-DOCP-TORA
               mac: 44:38:39:00:00:07
               network: net4
               remote_interface: swp49
       LINK: swp30
               remote_device: MDC1-19-DOCP-TORB
               mac: 44:38:39:00:00:1b
               network: net14
               remote_interface: swp49
       LINK: swp31
               remote_device: MDC1-22-OCP-ACCESSA
               mac: 44:38:39:00:00:10
               network: net8
               remote_interface: swp49
       LINK: swp32
               remote_device: MDC1-22-OCP-ACCESSB
               mac: 44:38:39:00:00:1a
               network: net13
               remote_interface: swp49
>> DEVICE: MDC1-19-OCP-SPINEB
     code: CumulusCommunity/cumulus-vx
     memory: 512
     function: spine
     hostname: MDC1-19-OCP-SPINEB
       LINK: swp1
               remote_device: MDC1-19-OCP-SPINEA
               mac: 44:38:39:00:00:14
               network: net10
               remote_interface: swp1
       LINK: swp27
               remote_device: RR3-05-QOCP-TORA
               mac: 44:38:39:00:00:1d
               network: net15
               remote_interface: swp50
       LINK: swp28
               remote_device: RR3-05-QOCP-TORB
               mac: 44:38:39:00:00:01
               network: net1
               remote_interface: swp50
       LINK: swp29
               remote_device: MDC1-19-DOCP-TORA
               mac: 44:38:39:00:00:21
               network: net17
               remote_interface: swp50
       LINK: swp30
               remote_device: MDC1-19-DOCP-TORB
               mac: 44:38:39:00:00:0b
               network: net6
               remote_interface: swp50
       LINK: swp31
               remote_device: MDC1-22-OCP-ACCESSA
               mac: 44:38:39:00:00:12
               network: net9
               remote_interface: swp50
       LINK: swp32
               remote_device: MDC1-22-OCP-ACCESSB
               mac: 44:38:39:00:00:0e
               network: net7
               remote_interface: swp50
>> DEVICE: MDC1-19-DOCP-TORB
     code: CumulusCommunity/cumulus-vx
     memory: 512
     function: leaf
     hostname: MDC1-19-DOCP-TORB
       LINK: swp47
               remote_device: MDC1-19-DOCP-TORA
               mac: 44:38:39:00:00:16
               network: net11
               remote_interface: swp47
       LINK: swp49
               remote_device: MDC1-19-OCP-SPINEA
               mac: 44:38:39:00:00:1c
               network: net14
               remote_interface: swp30
       LINK: swp50
               remote_device: MDC1-19-OCP-SPINEB
               mac: 44:38:39:00:00:0c
               network: net6
               remote_interface: swp30
>> DEVICE: MDC1-19-DOCP-TORA
     code: CumulusCommunity/cumulus-vx
     memory: 512
     function: leaf
     hostname: MDC1-19-DOCP-TORA
       LINK: swp47
               remote_device: MDC1-19-DOCP-TORB
               mac: 44:38:39:00:00:15
               network: net11
               remote_interface: swp47
       LINK: swp49
               remote_device: MDC1-19-OCP-SPINEA
               mac: 44:38:39:00:00:08
               network: net4
               remote_interface: swp29
       LINK: swp50
               remote_device: MDC1-19-OCP-SPINEB
               mac: 44:38:39:00:00:22
               network: net17
               remote_interface: swp29
>> DEVICE: RR3-05-QOCP-TORA
     code: CumulusCommunity/cumulus-vx
     memory: 512
     function: leaf
     hostname: RR3-05-QOCP-TORA
       LINK: swp49
               remote_device: MDC1-19-OCP-SPINEA
               mac: 44:38:39:00:00:18
               network: net12
               remote_interface: swp27
       LINK: swp50
               remote_device: MDC1-19-OCP-SPINEB
               mac: 44:38:39:00:00:1e
               network: net15
               remote_interface: swp27
       LINK: swp51
               remote_device: RR3-05-QOCP-TORB
               mac: 44:38:39:00:00:05
               network: net3
               remote_interface: swp51
       LINK: swp52
               remote_device: RR3-05-QOCP-TORB
               mac: 44:38:39:00:00:1f
               network: net16
               remote_interface: swp52
>> DEVICE: RR3-05-QOCP-TORB
     code: CumulusCommunity/cumulus-vx
     memory: 512
     function: leaf
     hostname: RR3-05-QOCP-TORB
       LINK: swp49
               remote_device: MDC1-19-OCP-SPINEA
               mac: 44:38:39:00:00:0a
               network: net5
               remote_interface: swp28
       LINK: swp50
               remote_device: MDC1-19-OCP-SPINEB
               mac: 44:38:39:00:00:02
               network: net1
               remote_interface: swp28
       LINK: swp51
               remote_device: RR3-05-QOCP-TORA
               mac: 44:38:39:00:00:06
               network: net3
               remote_interface: swp51
       LINK: swp52
               remote_device: RR3-05-QOCP-TORA
               mac: 44:38:39:00:00:20
               network: net16
               remote_interface: swp52
>> DEVICE: MTS1-20-HOCP-TORB
     code: CumulusCommunity/cumulus-vx
     memory: 512
     function: leaf
     hostname: MTS1-20-HOCP-TORB

############
SUCCESS: Vagrantfile has been generated!
############

DONE!

kevinw@Kevins-MBP-2[topology_converter]#

**Comment by ericpulvino** [comment]
Good find. I'm investigating this.

**Comment by ericpulvino** [comment]
This would actually require a surprising amount of work to code around and the values are not required for anything or even apparently used by Cumulus. I see they're in our docs however. Will follow up with Dinesh on this to get the values removed from documentation if they're truly non functional. I am going to close this for now because the workaround is easy, just remove the offending bit at the top.
