### ISSUE TITLE
Support defaults within a topology

### ISSUE THREAD

**Issue by plumbis** [CumulusNetworks/topology_converter#2]
It would be nice if function defaults could be defined and supported and then just override on a individual basis. 

For example, it would be great to define

```
graph dc1{
 "leaf1" [function="leaf"]
 "spine1" [function="spine"]

"leaf1":"swp1" -- "spine1":"swp1"
} 
```

based on only this definition it would assign things like `os=CumulusCommunity/cumulus-vx` and `memory=300`

**Comment by eric-cumulus** [comment]
Great idea. I thought about implementing a framework to do this...

`graph dc1{
 "leaf" [functional_default=True os="CumulusCommunity/cumulus-vx" memory="300"]
 "spine" [functional_default=True os="CumulusCommunity/cumulus-vx" memory="300"]
 "leaf1" [function="leaf"]
 "spine1" [function="spine"]
"leaf1":"swp1" -- "spine1":"swp1"
} `

That approach while probably more scalable and modular, seems like overkill and requires more of the user. So I settled on the syntax you specified.

Defaults:
- Leaf,Spine,Exit,oob-switch
`os="CumulusCommunity/cumulus-vx" memory="300"`
- Host,oob-server
`os="boxcutter/ubuntu1604" memory="500"`

**Comment by plumbis** [comment]
That's a good start. I like the idea of the more flexible default definitions you describe. It would lend itself to then make it easy to tie it into ansible group mappings (see #4)

**Comment by ericpulvino** [comment]
I'll keep it with the simple syntax for now as it puts less onus on the user but I'll keep this idea on the backburner if there's ever a compelling need.
