### ISSUE TITLE
ability to customize ssh port for remote access? 

### ISSUE THREAD

**Issue by wmclendon** [CumulusNetworks/topology_converter#27]
i'm not sure if this is possible via passthrough attributes, but i'm trying to use this to generate a Vagrantfile for running on an external device -- in this case an Intel NUC, so that I can leave it running for extended periods and access the devices remotely for Ansible playbook testing, etc.  For now manually adding the following statement for each device definition in the Vagrantfile (modify ssh port for each device), but hoping this can be done either via passthrough attributes or future feature addition

[add below line for each device defined in the vagrantfile]
device.vm.network :forwarded_port, guest: 22, host: 2204, host_ip: "0.0.0.0", id: "ssh", auto_correct:true

specifying a hardcoded ssh port allows me to define in ansible running on local laptop what port to connect to to make changes, the 'host_ip' portion allows anyone to SSH to the address.  I believe by default Vagrant only allows the localhost access.

**Comment by ericpulvino** [comment]
I like this idea. 
Not sure it can be done with a passthrough attribute but it can surely be done with a new optional node attribute. I think it also makes sense to use the ":auto_correct" option just in case there are conflicts in a concurrent simulation scenario. I'll implement this on the development branch soon!

**Comment by ericpulvino** [comment]
Thanks for the suggestion! 
This has been implemented so I'm closing this for now.
