### ISSUE TITLE
-c option incorrectly creates bridge with eth0 in it

### ISSUE THREAD

**Issue by seanx820** [CumulusNetworks/topology_converter#29]
`    bridge-ports glob swp1-48 eth0
`

this messed up some configuration for Attilla, not sure what is going on here... something could be hard codes with eth0.  Either way this is not possible in real hardware, you can't bridge eth0 and swp ports so lets remove the eth0 from this config.

**Comment by ericpulvino** [comment]
Resolved in development branch.
