### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by linuxsimba** [CumulusNetworks/topology_converter#3]
What is the project license? MIT, GPLv2? 

thanks.

**Comment by ericpulvino** [comment]
Just updated the repo /w the MIT license... had been meaning to do this, thanks for the reminder Stanley! Miss you!

**Comment by ericpulvino** [comment]
We have had requests from high up to change the license on this project to GPLv2.

**Comment by ericpulvino** [comment]
https://github.com/CumulusNetworks/topology_converter/commit/b52fbb860f50f4d0c933c1e9d555598cf95669fb#diff-9879d6db96fd29134fc802214163b95a Changes committed.
