### ISSUE TITLE
xenial  blows, 1404 for life

### ISSUE THREAD

**Issue by seanx820** [CumulusNetworks/topology_converter#30]
The rest of the consultants have voted while you were out and decided that we want 14.04 for life

`   inventory[mgmt_server]["os"] = "boxcutter/ubuntu1404"
        if provider=="libvirt":
            inventory[mgmt_server]["os"] = "boxcutter/ubuntu1404"
        inventory[mgmt_server]["memory"] = "512"
        inventory[mgmt_server]["config"] = "./helper_scripts/auto_mgmt_network/OOB_Server_Config_auto_mgmt.sh"`

**Comment by rdarbha** [comment]
:trollface:

**Comment by ericpulvino** [comment]
16.06 is the way forward and simplifies much. I must disagree here.
