### ISSUE TITLE
when using -c option setup ztp for mgmt vrf and keys 

### ISSUE THREAD

**Issue by seanx820** [CumulusNetworks/topology_converter#32]
#!/bin/bash
function error() {
  echo -e "\e[0;33mERROR: The Zero Touch Provisioning script failed while running the command $BASH_COMMAND at line $BASH_LINENO.\e[0m" >&2
}
trap error ERR
SSH_URL="http://192.168.0.254/authorized_keys"
#Setup SSH key authentication for Ansible
mkdir -p /root/.ssh
wget -O /root/.ssh/authorized_keys $SSH_URL
sed -i '/iface eth0/a \ vrf mgmt' /etc/network/interfaces
cat <<EOT >> /etc/network/interfaces
auto mgmt
iface mgmt
  address 127.0.0.1/8
  vrf-table auto
EOT
#reload networking
reboot
exit 0
#CUMULUS-AUTOPROVISIONING

**Comment by ericpulvino** [comment]
added in commit 80bbb3c05679c78b2863ccaa67b1755373357e6b
