### ISSUE TITLE
certain os (cough coreOS) don't have a plain-text pw

### ISSUE THREAD

**Issue by seanx820** [CumulusNetworks/topology_converter#33]
this creates a problem for our oob-mgmt networks.... i just added a simple 'bash' to the helper-sciprts (extra_server_config.sh)

```
#make sure there is a cumulus user on any *nix server  
useradd cumulus  
sudo echo -e 'CumulusLinux!\nCumulusLinux!' | passwd cumulus  
```

**Comment by seanx820** [comment]
actually talk to me before you implement this.... i got some other ideas

**Comment by seanx820** [comment]
for coreOS this is what we need to do for their official vagrant box images->

```bash
sudo echo -e 'CumulusLinux!\nCumulusLinux!' | passwd core
```

I added this to my extra_server_config

**Comment by ericpulvino** [comment]
I don't think this is a core functionality of topology_converter. This is good data however.
