### ISSUE TITLE
nic count

### ISSUE THREAD

**Issue by dsmarsh** [CumulusNetworks/topology_converter#35]
I was testing using breakout and needed more nics and didn't realize you set a hard limit.

Can we changes this to something absurdly high?
domain.nic_adapter_count = 55

**Comment by ericpulvino** [comment]
It is ironic. @linuxsimba told me the original vagrant-libvirt creator @pronix had said to always keep this value as low as possible. Perhaps @infernix knows...

**Comment by infernix** [comment]
Best guess? PCI(e) device count limits. Never tried though.

**Comment by ericpulvino** [comment]
I had it as high as 200 for scale testing... boot up was slow but I imagined that was more of a Linux concern than vagrant-libvirt or libvirt for that matter. I'll try setting up to 130 which for now which will allow us to simulate the next generation of network switches having ~128 ports (max).

**Comment by dsmarsh** [comment]
Changing this didn't effect my boot up times.

**Comment by pronix** [comment]
looks like in redhat kvm exists some limitations for nics amount https://access.redhat.com/articles/1436373

**Comment by infernix** [comment]
As long as qemu supports it and the kernel successfully enumerates, i think pci multifunctions (8) * assignable pci slots (28? 32?) is your limit.

**Comment by ericpulvino** [comment]
I seem to recall not noticing a difference until I actually created the interfaces.
