### ISSUE TITLE
Dynamically Create Ansible Groups

### ISSUE THREAD

**Issue by plumbis** [CumulusNetworks/topology_converter#4]
There are logical groupings already, these should be turned into Ansible groups within the vagrantfile.

Furthermore the device definitions should allow for a group list. Maybe something like

```
graph dc1{
 "leaf1" [function="leaf", group="A-leaf"]
 "leaf2" [function="leaf", group="B-leaf"]
 "spine1" [function="spine", group="A-leaf"]
 "spine2" [function="spine", group="B-leaf"]

...
} 
```

In this example leaf1 and leaf2 would belong to the group "leafs" as well as each leaf in an individual group.

**Comment by ericpulvino** [comment]
We support this today with [Passthrough Attributes](https://github.com/CumulusNetworks/topology_converter/tree/master/documentation#passthrough-attributes). 
These allow the user to specify any attribute they want and add the associated code in the templatefile (./templates/Vagrantfile.j2 ) to use their new attribute.

**Comment by ericpulvino** [comment]
Passthrough attributes are used here for for "mgmt_ip" and "ansible" here --> https://github.com/CumulusNetworks/cldemo-vagrant/blob/master/topology.dot

And then adds a snippet of code to the template file here to support his new attributes --> https://github.com/CumulusNetworks/cldemo-vagrant/blob/master/templates/Vagrantfile.j2#L73-L82
