### ISSUE TITLE
puppet in hosts file

### ISSUE THREAD

**Issue by dsmarsh** [CumulusNetworks/topology_converter#41]
/etc/hosts file contains puppet even when not using puppet:
```
{% set mgmt_ips = devices[0].mgmt_ip.split(',') -%}
{% for mgmt_ip in mgmt_ips %}
{{ mgmt_ip }} {{ devices[0].hostname }} puppet {% endfor %}

```

**Comment by ericpulvino** [comment]
Initially this was not a mistake. Have to look at how this can be moved into a specific puppet on the MGMT station workflow. Will evaluate this shortly.
