### ISSUE TITLE
Add range to fake device port mappings

### ISSUE THREAD

**Issue by dsmarsh** [CumulusNetworks/topology_converter#45]
I was thinking of a way to fix having to type out 48 ports since i put a range on my bridge config, and now each time I do `ifreload -a`, it fails, and I thought a swp/port range in the topo file might fix this.

> error: bridge: bridge port swp2 does not exist
> error: bridge: bridge port swp1 does not exist

This could go beyond fake devices as well I guess.

**Comment by ericpulvino** [comment]
Finished with the above commit.
