### ISSUE TITLE
documentation formatting

### ISSUE THREAD

**Issue by dsmarsh** [CumulusNetworks/topology_converter#59]
Not a big deal, but all your formatting is broken in the documentation folder.

**Comment by dsmarsh** [comment]
it also means all the anchors are borked too.

**Comment by ericpulvino** [comment]
Looks to be due to this. Github has standardized around a certain type of markdown... it seems to break headings in the majority of our repositories... https://githubengineering.com/a-formal-spec-for-github-markdown/

**Comment by ericpulvino** [comment]
Fixed on Master.
