### ISSUE TITLE
bridge-untagged fails to receive DHCP address

### ISSUE THREAD

**Issue by KyleMartin901** [CumulusNetworks/topology_converter#62]
Hi,

I have setup a basic topology and ran the topology converter with the `-c` option to configure the OOB management server and switches automatically.

    "core01" [function="spine" os="CumulusCommunity/cumulus-vx" version="3.3.0" memory="512" config="./helper_scripts/extra_switch_config.sh" mgmt_ip="192.168.200.10"]
    "core02" [function="spine" os="CumulusCommunity/cumulus-vx" version="3.3.0" memory="512" config="./helper_scripts/extra_switch_config.sh" mgmt_ip="192.168.200.11"]
    "sw01" [function="leaf" os="CumulusCommunity/cumulus-vx" version="3.3.0" memory="512" config="./helper_scripts/extra_switch_config.sh" mgmt_ip="192.168.200.12"]
    "sw02" [function="leaf" os="CumulusCommunity/cumulus-vx" version="3.3.0" memory="512" config="./helper_scripts/extra_switch_config.sh" mgmt_ip="192.168.200.13"]
 

I have witnessed that when the [topology_converter/helper_scripts/oob_switch_config.sh ](https://github.com/CumulusNetworks/topology_converter/blob/master/helper_scripts/oob_switch_config.sh) scrip runs and configures the bridge interface to use DHCP `sed -i 's/iface bridge-untagged/iface bridge-untagged inet dhcp/' /etc/network/interfaces.d/bridge` it is not assigned a DHCP address from the oob-mgmt-server.

When I set it to static and assign the IP address it works as expected.

**Comment by ericpulvino** [comment]
Looks like this is due to how the dhcp template is constructed. I'll remedy this for the next release.

**Comment by ericpulvino** [comment]
Should be fixed now.
