### ISSUE TITLE
Random Mac Addresses should be created with colon notation

### ISSUE THREAD

**Issue by isharacomix** [CumulusNetworks/topology_converter#7]
It's much easier in a template to strip out the colons than it is to add the colons. Perhaps when generating random mac addresses, we should generate them with the colons so that for places that need them (like isc-dhcp-server) we can leave the string along, and remove the colons in templates in other places (such as kvm nic entries) using `.replace(':','')`.

If you don't get to it before I do, I'll make a PR.

**Comment by eric-cumulus** [comment]
Great idea.... apply udev is set to take either or I believe.

**Comment by ericpulvino** [comment]
Started to poke at this for an engagement... will submit code soon.

**Comment by ericpulvino** [comment]
Added this in Commit b097b706ae3da0dde3cf91235301258a2240b226 take a look and tell me what you think.

**Comment by ericpulvino** [comment]
Haven't heard anything so going to close as complete.
