### ISSUE TITLE
cant bring up oob-mgmt-switch due to interface count

### ISSUE THREAD

**Issue by wmclendon** [CumulusNetworks/topology_converter#70]
Hello,

i'm trying to use the '-c' option, and when I am trying to boot up the oob-mgmt-switch, I get the following error:

==> oob-mgmt-switch: Checking if box 'CumulusCommunity/cumulus-vx' is up to date...
==> oob-mgmt-switch: Setting the name of the VM: 1505846706_oob-mgmt-switch
==> oob-mgmt-switch: Fixed port collision for 22 => 2222. Now on port 2206.
==> oob-mgmt-switch: Clearing any previously set network interfaces...
There is no available slots on the VirtualBox VM for the configured
high-level network interfaces. "private_network" and "public_network"
network configurations consume a single network adapter slot on the
VirtualBox VM. VirtualBox limits the number of slots to 8, and it
appears that every slot is in use. Please lower the number of used
network adapters.

in my DOT file I have a large number of 'fake' devices defined so that the appropriate cumulus switch interfaces get configured.  Looking at the Vagrantfile, it seems each of these is defined to get a connection to the oob-mgmt-switch, which I do not require.  For example:

      # link for swp27 --> vmhost03:eth0
      device.vm.network "private_network", virtualbox__intnet: "#{simid}_net152", auto_config: false , :mac => "44383900012d"

is listed in the oob-mgmt-switch config section.  Is there some setting I overlooked, that I need to add to the fake devices so they don't get an interface assigned?

**Comment by ericpulvino** [comment]
This error comes from one of two sources:

1). Old version of Virtualbox -- Try updating to the latest version --> https://www.virtualbox.org/wiki/Downloads
2). Too many interfaces on the OOB-mgmt-switch device. Lower the number of interfaces you are trying to simulate with your "fake" interfaces. In recent versions of Virtualbox [the true limit of interfaces is 36](https://github.com/CumulusNetworks/topology_converter/tree/master/documentation#miscellaneous-info), more than 36 and the machine cannot start. The libvirt/KVM hypervisor has no interface limits for better scale but it can be a bit more difficult to get started feel free to checkout [our article on the topic](https://getsatisfaction.cumulusnetworks.com/cumulus/topics/setting-up-an-ubuntu-16-04-server-for-simulation-with-libvirt-kvm) if that's something you've been thinking about.

Let me know what you find.

**Comment by wmclendon** [comment]
looks like my version of Virtual Box is 4.3.36 running on Ubuntu 14 on my NUC that I use.

I'm definitely over the 36 interface limit as my DOT file is configured right now.  I do have a lot of fake devices defined, as I want the lab topology not to bark about interfaces not existing during ifreloads, etc.  I might be able to trim some of it out to get under 36.  Would it be possible to make it so that 'fake' device types don't get allocated an interface on the oob-mgmt-switch?  without fake devices i'm down in the 8-10 range of devices that need to connections to the oob-mgmt-switch.  defining Fake devices for purposes of interfaces getting created on the VX and having too many fake devices causing oob-mgmt-switch to be unusable seem to be features at odds with each other.

I have another intel NUC not doing anything right now.  May load up Ubuntu 16 with KVM in the next week or so and see how that works

**Comment by ericpulvino** [comment]
Restating what I think you said, I believe your point makes sense.... Fake devices should not get an oob-mgmt-switch port allocated. I'll poke at this shortly.

**Comment by wmclendon** [comment]
yes that is correct -- thank you for taking a look.

Also, thanks for this great tool.  It's been tremendously helpful in labbing up our production environment in virtual space to test proposed changes.

**Comment by ericpulvino** [comment]
Very glad it is useful to you!
