### ISSUE TITLE
cannot stat ‘/home/vagrant/bridge-untagged’

### ISSUE THREAD

**Issue by sanderboele** [CumulusNetworks/topology_converter#76]
https://github.com/CumulusNetworks/topology_converter/blob/1b420de7cc1c66885a7050ba659d61ce42abbe2a/helper_scripts/oob_switch_config.sh#L28

This file does not exist

**Comment by ericpulvino** [comment]
This file is created when used with the Auto Management Network flags. See the docs here: https://github.com/CumulusNetworks/topology_converter/tree/master/documentation/auto_mgmt_network

The following template is rendered to create the file --> https://github.com/CumulusNetworks/topology_converter/blob/master/templates/auto_mgmt_network/bridge-untagged.j2
