### ISSUE TITLE
if bonds are up apply_udev will not work

### ISSUE THREAD

**Issue by seanx820** [CumulusNetworks/topology_converter#9]
`[root@server01 vagrant]# ./apply_udev.py
Cannot get driver information: No such device
 ### ERROR Tried 3 methods to determine device driver. All Failed.
[root@server01 vagrant]# ls
apply_udev.py  sync
[root@server01 vagrant]# ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
14: vagrant: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000
    link/ether 52:54:00:96:1d:95 brd ff:ff:ff:ff:ff:ff
15: bond0.401: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 3a:6d:37:d8:95:0f brd ff:ff:ff:ff:ff:ff
16: bond0.403: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 7e:72:39:b4:9b:8b brd ff:ff:ff:ff:ff:ff
17: bond0.408: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 5e:59:bd:49:8a:a7 brd ff:ff:ff:ff:ff:ff
18: bond0.404: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 26:4a:28:6f:82:27 brd ff:ff:ff:ff:ff:ff
19: bond0.402: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 7e:f5:43:d4:2b:04 brd ff:ff:ff:ff:ff:ff
21: bond0.412: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 5e:26:5c:da:16:5f brd ff:ff:ff:ff:ff:ff
22: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
23: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000
    link/ether a0:00:00:00:00:31 brd ff:ff:ff:ff:ff:ff
24: eth1: <BROADCAST,MULTICAST,PROMISC,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master bond0 state UP mode DEFAULT qlen 1000
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
25: eth2: <BROADCAST,MULTICAST,PROMISC,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master bond0 state UP mode DEFAULT qlen 1000
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
27: bond0.400@bond0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
[root@server01 vagrant]# ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
14: vagrant: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000
    link/ether 52:54:00:96:1d:95 brd ff:ff:ff:ff:ff:ff
15: bond0.401: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 3a:6d:37:d8:95:0f brd ff:ff:ff:ff:ff:ff
16: bond0.403: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 7e:72:39:b4:9b:8b brd ff:ff:ff:ff:ff:ff
17: bond0.408: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 5e:59:bd:49:8a:a7 brd ff:ff:ff:ff:ff:ff
18: bond0.404: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 26:4a:28:6f:82:27 brd ff:ff:ff:ff:ff:ff
19: bond0.402: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 7e:f5:43:d4:2b:04 brd ff:ff:ff:ff:ff:ff
21: bond0.412: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 5e:26:5c:da:16:5f brd ff:ff:ff:ff:ff:ff
22: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
23: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000
    link/ether a0:00:00:00:00:31 brd ff:ff:ff:ff:ff:ff
24: eth1: <BROADCAST,MULTICAST,PROMISC,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master bond0 state UP mode DEFAULT qlen 1000
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
25: eth2: <BROADCAST,MULTICAST,PROMISC,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master bond0 state UP mode DEFAULT qlen 1000
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
27: bond0.400@bond0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
[root@server01 vagrant]# ip link del bond0.401
[root@server01 vagrant]# ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
14: vagrant: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000
    link/ether 52:54:00:96:1d:95 brd ff:ff:ff:ff:ff:ff
16: bond0.403: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 7e:72:39:b4:9b:8b brd ff:ff:ff:ff:ff:ff
17: bond0.408: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 5e:59:bd:49:8a:a7 brd ff:ff:ff:ff:ff:ff
18: bond0.404: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 26:4a:28:6f:82:27 brd ff:ff:ff:ff:ff:ff
19: bond0.402: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 7e:f5:43:d4:2b:04 brd ff:ff:ff:ff:ff:ff
21: bond0.412: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 5e:26:5c:da:16:5f brd ff:ff:ff:ff:ff:ff
22: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
23: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000
    link/ether a0:00:00:00:00:31 brd ff:ff:ff:ff:ff:ff
24: eth1: <BROADCAST,MULTICAST,PROMISC,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master bond0 state UP mode DEFAULT qlen 1000
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
25: eth2: <BROADCAST,MULTICAST,PROMISC,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master bond0 state UP mode DEFAULT qlen 1000
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
27: bond0.400@bond0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
[root@server01 vagrant]# ip link del bond0.403
[root@server01 vagrant]# ip link del bon0.408
Cannot find device "bon0.408"
[root@server01 vagrant]# ip link del bon0.404
Cannot find device "bon0.404"
[root@server01 vagrant]# ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
14: vagrant: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000
    link/ether 52:54:00:96:1d:95 brd ff:ff:ff:ff:ff:ff
17: bond0.408: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 5e:59:bd:49:8a:a7 brd ff:ff:ff:ff:ff:ff
18: bond0.404: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 26:4a:28:6f:82:27 brd ff:ff:ff:ff:ff:ff
19: bond0.402: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 7e:f5:43:d4:2b:04 brd ff:ff:ff:ff:ff:ff
21: bond0.412: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 5e:26:5c:da:16:5f brd ff:ff:ff:ff:ff:ff
22: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
23: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000
    link/ether a0:00:00:00:00:31 brd ff:ff:ff:ff:ff:ff
24: eth1: <BROADCAST,MULTICAST,PROMISC,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master bond0 state UP mode DEFAULT qlen 1000
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
25: eth2: <BROADCAST,MULTICAST,PROMISC,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master bond0 state UP mode DEFAULT qlen 1000
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
27: bond0.400@bond0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
[root@server01 vagrant]# ip link del bond0.412
[root@server01 vagrant]# ip link del bond0.404
[root@server01 vagrant]# ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
14: vagrant: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000
    link/ether 52:54:00:96:1d:95 brd ff:ff:ff:ff:ff:ff
17: bond0.408: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 5e:59:bd:49:8a:a7 brd ff:ff:ff:ff:ff:ff
19: bond0.402: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 7e:f5:43:d4:2b:04 brd ff:ff:ff:ff:ff:ff
22: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
23: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000
    link/ether a0:00:00:00:00:31 brd ff:ff:ff:ff:ff:ff
24: eth1: <BROADCAST,MULTICAST,PROMISC,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master bond0 state UP mode DEFAULT qlen 1000
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
25: eth2: <BROADCAST,MULTICAST,PROMISC,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master bond0 state UP mode DEFAULT qlen 1000
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
27: bond0.400@bond0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
[root@server01 vagrant]# ip link del bond0.408
[root@server01 vagrant]# ip link del bond0.402
[root@server01 vagrant]# ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
14: vagrant: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000
    link/ether 52:54:00:96:1d:95 brd ff:ff:ff:ff:ff:ff
22: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
23: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000
    link/ether a0:00:00:00:00:31 brd ff:ff:ff:ff:ff:ff
24: eth1: <BROADCAST,MULTICAST,PROMISC,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master bond0 state UP mode DEFAULT qlen 1000
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
25: eth2: <BROADCAST,MULTICAST,PROMISC,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master bond0 state UP mode DEFAULT qlen 1000
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
27: bond0.400@bond0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
[root@server01 vagrant]# ip link del bond0
[root@server01 vagrant]# ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
14: vagrant: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000
    link/ether 52:54:00:96:1d:95 brd ff:ff:ff:ff:ff:ff
23: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000
    link/ether a0:00:00:00:00:31 brd ff:ff:ff:ff:ff:ff
24: eth1: <BROADCAST,MULTICAST,PROMISC> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT qlen 1000
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
25: eth2: <BROADCAST,MULTICAST,PROMISC> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT qlen 1000
    link/ether 44:38:39:00:00:0b brd ff:ff:ff:ff:ff:ff
[root@server01 vagrant]# ./apply_udev.py
  INFO: Applying new UDEV Rules...
  INFO: Adding UDEV Rule: 52:54:00:96:1d:95 --> vagrant
          FYI: vagrant will become the vagrant interface
### PRESENT INTERFACES ###
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
28: vagrant: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000
    link/ether 52:54:00:96:1d:95 brd ff:ff:ff:ff:ff:ff
29: bond0.402: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 6a:f0:f8:28:2a:61 brd ff:ff:ff:ff:ff:ff
30: bond0.408: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 22:7e:4c:12:38:3c brd ff:ff:ff:ff:ff:ff
31: bond0.404: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 66:74:36:a5:e2:dc brd ff:ff:ff:ff:ff:ff
32: bond0.412: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether d2:22:5d:36:8f:66 brd ff:ff:ff:ff:ff:ff
33: bond0.403: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 2e:23:8c:24:b2:6e brd ff:ff:ff:ff:ff:ff
34: bond0.401: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 96:5a:c7:17:fd:86 brd ff:ff:ff:ff:ff:ff
35: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000
    link/ether a0:00:00:00:00:31 brd ff:ff:ff:ff:ff:ff
36: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000
    link/ether 44:38:39:00:00:1e brd ff:ff:ff:ff:ff:ff
37: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT qlen 1000
    link/ether 44:38:39:00:00:0b brd ff:ff:ff:ff:ff:ff`

**Comment by ericpulvino** [comment]
Digging into these outputs I think I understand the problem now.

**Comments:**
-Apply_udev was meant to build UDEV rules for explicit application at boot time.
-The "--apply" action was meant for those cases where a freshly started VM has compiled the drivers (that are supporting the network interfaces) as modules that can be unloaded. This allows for UDEV rules to be applied without a reboot.

**Questions:**
-Does a reboot work to apply the rules instead of the "--apply" action?What happens during a reboot of the VM after the rules have been written to the udev rules file, are the udev rules applied correctly?

**Comment by seanx820** [comment]
>
> -Does a reboot work to apply the rules instead of the "--apply"
> action?What happens during a reboot of the VM after the rules have been
> written to the udev rules file, are the udev rules applied correctly?
>

no they are not applied with a reboot, my playbooks have to manually call
it each time :-/

**Comment by ericpulvino** [comment]
Sounds like a host issue if UDEV rules are not being properly applied at boot. Would like to debug with you further in person. Check the "journalctl | grep udev" if the device is using Systemd, otherwise check the /var/log/syslog outputs after a reboot to see what might be going wrong.

Going to close as won't fix for now.
