### ISSUE TITLE
Workaround ZTP 3.6.0

### ISSUE THREAD

**Issue by packetninja** [CumulusNetworks/topology_converter#97]
In 3.6.0 ZTP doesn't work consistently with the vagrant image. If the following is added to the Vagrantfile.j2 template, this is solved.

`            if [[ $DISTRIB_RELEASE =~ ^3.6.0 ]]; then
                if [ "$HOSTNAME" != oob-mgmt-switch ]; then
                    ztp -R
                    ztp -i
                fi
            fi`

**Comment by ericpulvino** [comment]
This is addressed in commit --> https://github.com/CumulusNetworks/topology_converter/commit/5a924e502b80620484fc22d26b904e22a96b93b0
