### ISSUE TITLE
Auto login to cumulus user on oob-server

### ISSUE THREAD

**Issue by packetninja** [CumulusNetworks/topology_converter#99]
Currently, after a topology is generated, there is no auto login to the cumulus user when doing a "vagrant ssh oob-mgmt-server". Dit can be solved by adding the following to the "OOB server Config" template.

echo "sudo su - cumulus" >> /home/vagrant/.bash_profile
echo "exit" >> /home/vagrant/.bash_profile

**Comment by ericpulvino** [comment]
This approach actually breaks things like Vagrant SCP plugin which is used by some. If you can come up with another approach that doesn't sever that functionality I'm all ears.

**Comment by packetninja** [comment]
I don't have a better solution than this. It would be for a use-case where I build an environment for a customer and give them remote access. Would a flag be an option?

**Comment by ericpulvino** [comment]
This needs to be fixed in the image. See https://tickets.cumulusnetworks.com/browse/CM-13454 Scheduled for Banana. Closing for now.
